import "./CoreTest.js"
import "./Core/ClockTest.js"
import "./Core/DiceTest.js";
import "./Core/MainTest.js";
import "./Core/UtilsTest.js";
import "./DataTest.js"
import "./Data/DataBaseTest.js";
import "./Data/DataLibraryTest.js"
import "./Data/DataManagerTest.js"
import "./Data/XMLManagerTest.js"
import "./Data/TypesTest.js"
import "./Data/Types/AnimationGroupDataTest.js"
import "./Data/Types/AnimationTypeDataTest.js"
import "./Data/Types/BasicAttributeDataTest.js"
import "./Data/Types/ColorDataTest.js"
import "./Data/Types/CreatureDataTest.js"
import "./Data/Types/CreatureSizeDataTest.js"
import "./Data/Types/FontDataTest.js"
import "./Data/Types/FurnitureDataTest.js"
import "./Data/Types/GivenNameGroupDataTest.js"
import "./Data/Types/MaterialClassDataTest.js"
import "./Data/Types/MaterialDataTest.js"
import "./Data/Types/ModelDataTest.js"
import "./Data/Types/MusicDataTest.js"
import "./Data/Types/SurfaceTypeDataTest.js"
import "./Data/Types/TextureDataTest.js"
import "./Data/Types/TextureGridDataTest.js"
import "./Data/Types/TextureSheetDataTest.js"
import "./Data/Types/TreeDataTest.js"
import "./GameStateTest.js"
import "./GameState/ActorTest.js";
import "./GameState/CitizenTest.js";
import "./GameState/GameTest.js";
import "./GameState/GenderTest.js";
import "./GameState/PawnTest.js";
import "./GameState/SaveGameHeaderTest.js";
import "./GameState/SettlementTest.js";
import "./GameState/TemporalTest.js";
import "./GameState/TickerTest.js";
import "./GameState/WeatherTest.js";
import "./InterfaceTest.js"
import "./Interface/GameCameraTest.js";
import "./Interface/GameCameraStateTest.js";
import "./Interface/TerrainSlicerTest.js";
import "./Interface/VolumeSelectionTest.js";
import "./JobsTest.js"
import "./Jobs/ExcavateJobTest.js"
import "./Jobs/JobTest.js"
import "./Jobs/JobManagerTest.js"
import "./Jobs/LoiterJobTest.js"
import "./Jobs/TaskTest.js"
import "./Jobs/WanderJobTest.js"
import "./MapTest.js"
import "./Map/CoordinatesTest.js"
import "./Map/Coordinates/AxisTest.js";
import "./Map/Coordinates/BlockCoordinateTest.js";
import "./Map/Coordinates/ChunkCoordinateTest.js";
import "./Map/Coordinates/FaceCoordinateTest.js";
import "./Map/Coordinates/DirectionTest.js";
import "./Map/Coordinates/MapCoordinateTest.js";
import "./Map/Coordinates/RegionCoordinateTest.js";
import "./Map/Coordinates/SectorCoordinateTest.js";
import "./Map/BlockShapeTest.js";
import "./Map/ChunkTest.js";
import "./Map/FaceTest.js";
import "./Map/FaceShapeTest.js";
import "./Map/GameMapTest.js";
import "./Map/SectorTest.js";
import "./Map/TileBuilderTest.js";
import "./Map/ZoneTest.js";
import "./NiftyTest.js"
import "./Nifty/ChooseCitizenControlControllerTest.js";
import "./Nifty/CitizenWindowControllerTest.js";
import "./Nifty/ErrorPopupControllerTest.js";
import "./Nifty/GameScreenControllerTest.js";
import "./Nifty/GUITest.js";
import "./Nifty/KeyBoardMappingTest.js";
import "./Nifty/LoadGameScreenControllerTest.js";
import "./Nifty/MenuPopupControllerTest.js";
import "./Nifty/PopulationPopupControllerTest.js";
import "./Nifty/SetupScreenControllerTest.js";
import "./Nifty/ShellScreenControllerTest.js";
import "./Nifty/TutorialPopupControllerTest.js";
import "./Nifty/UpdatableTest.js";
import "./PathFindingTest.js"
import "./PathFinding/AStarTest.js";
import "./PathFinding/AStarNodeTest.js";
import "./PathFinding/CoordinatePathTest.js";
import "./PathFinding/CoordinatePathWalkerTest.js";
import "./PathFinding/GridInterfaceTest.js";
import "./PathFinding/HeuristicTest.js";
import "./PathFinding/KhazadGridTest.js";
import "./PathFinding/LinkedListDequeTest.js";
import "./PathFinding/MapPathTest.js";
import "./PathFinding/MovementModalityTest.js";
import "./PathFinding/NavigatorTest.js";
import "./PathFinding/PathAlgorithmTest.js";
import "./PathFinding/PathManagerTest.js";
import "./PathFinding/PathTesterTest.js";
import "./PathFinding/PathWalkerTest.js";
import "./PathFinding/PoolTest.js";
import "./PathFinding/RouteRequestTest.js";
import "./PathFinding/VectorPathTest.js";
import "./PathFinding/VectorPathWalkerTest.js";
import "./RendererTest.js"
import "./Renderer/ActorRendererTest.js";
import "./Renderer/ImageManagerTest.js";
import "./Renderer/MapRendererTest.js";
import "./Renderer/MapSlicerTest.js";
import "./Renderer/PathingRendererTest.js";
import "./Renderer/SelectionRendererTest.js";
import "./Renderer/TerrainBuilderTest.js";
import "./Renderer/TerrainDestroyerTest.js";
import "./Renderer/TerrainRendererTest.js";
import "./Renderer/TextureManagerTest.js";
import "./SoundTest.js"
import "./Sound/MusicTest.js";
import "./TerrainTest.js"
import "./Terrain/GeologyTest.js";
import "./Terrain/NoiseTest.js";
import "./otherTest.js"
import "./other/EnumTest.js";
import "./other/IntegersTest.js";
import "./other/AbstractClassTest.js";
import "./other/SerializableTest.js";
import "./other/ComparableTest.js";